export const ButtonStyles = {
  // styles for different sizes ("sm", "md", "lg")
  sizes: {},
  // styles for different visual variants ("outline", "solid")
  variants: {
    new: {
      bg: "primary",
      color: "white",
      paddingY: "2px",
      paddingX: "3px",
      borderRadius: "3px",
      lineHeight: "10px",
      height: "auto",
      marginRight: "4px",
    },
    inProgress: {
      bg: "yellow",
      color: "black",
      paddingY: "2px",
      paddingX: "3px",
      borderRadius: "3px",
      lineHeight: "10px",
      height: "auto",
      marginRight: "4px",
    },
    finished: {
      bg: "green",
      color: "white",
      paddingY: "2px",
      paddingX: "3px",
      borderRadius: "3px",
      lineHeight: "10px",
      height: "auto",
      marginRight: "4px",
    },
    low: {
      bg: "blue",
      color: "white",
      paddingY: "2px",
      paddingX: "3px",
      borderRadius: "3px",
      lineHeight: "10px",
      height: "auto",
      marginRight: "4px",
    },
    medium: {
      bg: "green",
      color: "white",
      paddingY: "2px",
      paddingX: "3px",
      borderRadius: "3px",
      lineHeight: "10px",
      height: "auto",
      marginRight: "4px",
    },
    high: {
      bg: "primary",
      color: "white",
      paddingY: "2px",
      paddingX: "3px",
      borderRadius: "3px",
      lineHeight: "10px",
      height: "auto",
      marginRight: "4px",
    },
  },
};
